### ISSUE TITLE
"Alert" component - Firefox layout issue

### ISSUE THREAD

**Issue by samburgers** [shadcn/ui#247] opened 2023-04-25 03:11 UTC
Noticed some layout issues in firefox with these components

https://ui.shadcn.com/docs/components/alert

<img width="685" alt="Screenshot 2023-04-25 at 1 10 59 pm" src="https://user-images.githubusercontent.com/1476939/234165160-107e5696-ecb7-4de6-8f3e-357ef4a0e85f.png">
<img width="689" alt="Screenshot 2023-04-25 at 1 10 23 pm" src="https://user-images.githubusercontent.com/1476939/234165169-f365a8a5-1d2a-4061-8fe3-4094603c84ce.png">

**Comment by emicba** [comment] 2023-04-25 13:43
This is a duplicate of #181

**Closed** 2023-05-01 12:21 UTC
